djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('test_task.urls'))
]

test_task/urls.py
from django.urls import path
from test_task import views

urlpatterns = [
    path('', views.calculate, name='home'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('history/', views.history, name='history'),
    path('details/<str:acc_id>/', views.details, name='details'),
]

test_task/models.py
from django.contrib.auth.models import User
from django.db import models


class Score(models.Model):
    account_number = models.CharField('Номер счета', max_length=16)
    balance = models.DecimalField('Баланс', max_digits=6, decimal_places=2)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Счет"
        verbose_name_plural = "Счета"

    def __str__(self):
        return str(self.account_number)


class TranslationHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    score_sender = models.ForeignKey(Score, on_delete=models.CASCADE)
    score_recipient = models.ForeignKey(Score, on_delete=models.CASCADE, related_name='set_recipient')
    amount = models.DecimalField('Сумма', max_digits=6, decimal_places=2)
    created_at = models.DateTimeField('Время транзакции', auto_now_add=True)

    class Meta:
        verbose_name = "История перевода"
        verbose_name_plural = "История переводов"

test_task/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class NameForm(forms.Form):
    amount = forms.DecimalField(label='Сумма перевода', min_value=0, max_value=9999999)


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Подтверждения пароля', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

test_task/views.py
from django.db.models import Q
from django.contrib.auth import logout, login
from django.contrib.auth.views import LoginView
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from test_task.forms import NameForm, RegisterUserForm, LoginUserForm
from test_task.models import User, Score, TranslationHistory
import urllib


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'test_task/register.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('home')


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'test_task/login.html'

    def get_success_url(self):
        return reverse_lazy('home')


def logout_user(request):
    logout(request)
    return redirect('login')


def calculate(request):
    authenticated_user_id = request.user.id  # id авторизированный пользователь
    recipients = Score.objects.exclude(user_id=authenticated_user_id)  # id счетов НЕ авторизированных пользователей

    if request.method == 'POST':
        amount = request.POST['amount']  # сумма перевода
        your_accounts = request.POST.getlist('your_accounts')  # id счетов авторизированного пользователя
        transfer_score_id = request.POST['transfer']  # id_счета кому переводим
        transactions(your_accounts, amount, transfer_score_id, authenticated_user_id)

    data = {
        'form': NameForm(),
        'recipients': recipients,
    }
    return render(request, 'test_task/home.html', data)


def transactions(your_accounts, amount, transfer_score_id, authenticated_user_id):
    account_len = len(your_accounts)  # коль-во выбранных счетов
    i = int(amount) / account_len  # сумму делим на коль-во аккаунтов
    selected_accounts = Score.objects.filter(id__in=your_accounts)  # querySet id выбранных аккаунтов
    for selected_account in selected_accounts:
        if selected_account.balance < i:
            raise Exception('insufficient funds!')

        selected_account.balance = float(selected_account.balance) - i
        selected_account.save()
        account_transfer = Score.objects.get(id=transfer_score_id)
        account_transfer.balance = float(account_transfer.balance) + i
        account_transfer.save()
        save_transactions(user=authenticated_user_id, score_sender=selected_account,
                          score_recipient=account_transfer, amount=i)


def save_transactions(user, score_sender, score_recipient, amount):
    return TranslationHistory.objects.create(user_id=user, score_sender=score_sender,
                                             score_recipient=score_recipient, amount=amount)


def history(request):
    q = request.GET.get('q', '')
    if q:
        history_filter = request.user.translationhistory_set.filter(
            Q(score_sender__account_number__icontains=q) |
            Q(amount=q)).order_by('-id')
    else:
        history_filter = request.user.translationhistory_set.all().order_by('-id')

    paginator = Paginator(history_filter, 6)
    page_number = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)

    from urllib.parse import urlencode
    params = {'q': q}
    q = urlencode(params)
    print(q)
    data = {
        'page_obj': page_obj,
        'q': q
    }
    return render(request, 'test_task/history.html', data)


def details(request, acc_id):
    score = Score.objects.filter(account_number=acc_id)

    data = {
        'score': score
    }
    return render(request, 'test_task/details_accounts.html', data)

test_task/templates/test_task/details_accounts.html
{% extends 'test_task/home.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            {% for foo in score %}
                <p><h6>Пользователь:{{ foo.user }}</h6>
                <p><h6>Номер счета: {{ foo.account_number }}</h6>
                <p><h6>Баланс: {{ foo.balance }}</h6>
            {% endfor %}
        </div>
    </div>


{% endblock %}

test_task/templates/test_task/history.html
{% extends 'test_task/home.html' %}


{% block content %}
    <div class="container">
        <form action="{% url 'history' %}" method="get">
            <div class="row">
                <div class="col-3">
                    <input class="form-control mr-sm-2" type="search" placeholder="Поиск" aria-label="Search" name="q">
                </div>
                <div class="col">
                    <button class="btn btn-outline-success my-2 my-sm-0 btn-block" type="submit">Поиск</button>
                </div>
            </div>



        <table class="table">
            <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">Отправитель</th>
                <th scope="col">Счет отправителя</th>
                <th scope="col">Получатель</th>
                <th scope="col">Счет получателя</th>
                <th scope="col">Сумма перевода</th>
                <th scope="col">Дата транзакции</th>
            </tr>
            </thead>
            <tbody>
            {% for history in page_obj.object_list %}
                <tr>
                    <th scope="row">{{ history.id }}</th>
                    <td>{{ history.user }}</td>
                        <td>
                            <a href="{% url 'details' history.score_sender %}">
                                {{ history.score_sender.account_number }}
                            </a>
                        </td>
                    <td>{{ history.score_recipient.user }}</td>
                    <td>{{ history.score_recipient.account_number }}</td>
                    <td>{{ history.amount }}</td>
                    <td>{{ history.created_at }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <!------------------------ Пагинация ------------------------>
        {% if page_obj.has_other_pages %}
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">

                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if q != '' %}&{{q}}{% endif %}"
                               tabindex="-1">Предыдущая</a>
                        </li>
                    {% endif %}


                    {% for p in page_obj.paginator.page_range %}

                        {% if page_obj.number == p %}
                            <li class="page-item active" aria-current="page">
                                <a class="page-link" href="?page={{ p }}">{{ p }}
                                    <span class="sr-only"></span> </a>
                            </li>

                        {% elif p > page_obj.number|add:-3 and p < page_obj.number|add:3 %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ p }}{% if q != '' %}&{{q}}{% endif %}">{{ p }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if q != '' %}&{{q}}{% endif %}">Следующая</a>
                        </li>
                    {% endif %}

                </ul>
            </nav>
        {% endif %}
        <!------------------------ end Пагинация ------------------------>
        </form>
    </div>
{% endblock %}

test_task/templates/test_task/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
</head>
<body>

{% include 'test_task/navbar.html' %}

{% block content %}
    <div class="container">
        {% if request.user.is_authenticated %}
            <form action="" method="POST">{% csrf_token %}
            <div>

                <hr>
                <label>
                    <h3>Ваши счета:</h3>
                    Выберите один или несколько своих счетов:
                    <select multiple="multiple" class="form-select form-select-sm"
                            aria-label=".form-select-lg example" name="your_accounts">

                        {% for account in user.score_set.values %}

                            <option value={{ account.id }}>
                                {{ account.account_number }}
                                баланс: {{ account.balance }}$
                            </option>

                        {% endfor %}
                    </select>
                </label>

                {% if messages %}
                    <div class="alert alert-danger" role="alert">
                        {% for message in messages %}
                            {{ message }}
                            {% if message.error %}
                                {{ message.error }}
                            {% endif %}
                            {{ message }}
                        {% endfor %}
                    </div>
                {% endif %}

            </div>

            <hr>

            <div>
                {{ form.amount }}
            </div>

            <hr>

            <div>

                Кому переводить:

                <label>
                    <select name="transfer">
                        <option disabled="disabled" selected="selected">Выбрать получателя</option>
                        {% for recipient in recipients %}
                            <option value="{{ recipient.id }}">{{ recipient.user }} - {{ recipient.account_number }}
                                - {{ recipient.balance }}$
                            </option>
                        {% endfor %}
                    </select>
                </label>

            </div>

            <hr>

            <div class="row">
                <div class="col">
                    <button class="btn btn-success" type="submit">Отправить</button>
                </div>
            </div>
        {% endif %}
        </form>
    </div>
{% endblock %}
</body>
</html>

test_task/templates/test_task/login.html
{% extends 'test_task/home.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <h2 class="text-center">Авторизация</h2>
            <div class="col-3">
                <form method="post">
                    {% csrf_token %}

                    <div class="form-error">{{ form.non_field_errors }}</div>

                    {% for f in form %}
                        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</p>
                        <div class="form-error">{{ f.errors }}</div>
                    {% endfor %}
                    <button class="btn btn-primary" type="submit">Войти</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

test_task/templates/test_task/navbar.html
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="/">Банк</a>

        {% if request.user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'history' %}">История переводов</a>
        {% endif %}


        <li class="nav">
            {% if request.user.is_authenticated %}
                <span class="navbar text black" style="font-size:19px">Здравствуйте, <span class="badge badge-danger">
                    <a style="text-decoration: none; font-size:20px; color:blue" href="#">{{ request.user.username }}!</a>
                </span><a href="{% url 'logout' %}" style="color:black; text-decoration: none; font-size:19px">Выйти</a></span>
         </li>
            {% endif %}
        {% if not request.user.is_authenticated %}

                <li style="list-style-type: none;">
                    <a class="" href="{% url 'login' %}" style="text-decoration: none;">Авторизация</a>
                </li>

                <li style="list-style-type: none;">
                    <a class="" href="{% url 'register' %}" style="text-decoration: none;">Регистрация</a>
                </li>


        {% endif %}
    </div>
</nav>

test_task/templates/test_task/register.html
{% extends 'test_task/home.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
        <h2 class="text-center">Регистрация нового пользователя</h2>
            <div class="col-3">
                <form action="" method="POST" class="text-center">
                    {% csrf_token %}
                    {% for f in form %}
                        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</p>
                        <div class="form-error">{{ f.errors }}</div>
                    {% endfor %}
                    <button class="btn btn-primary" type="submit">Регистрация</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}